name: Android Build

on:
  push:
    branches:
      - '*'
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set env variable
        run: echo '::set-env name=HAS_DEBUG_ARTIFACT::false' && echo '::set-env name=HAS_RELEASE_ARTIFACT::false'

      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        working-directory: android
        run: chmod +x gradlew

      - name: Run test
        if: ${{success()}}
        working-directory: android
        run: ./gradlew test

      # Debug APK

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug --stacktrace

      - name: Get Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: ./android/app/build/outputs/apk/debug/app-debug.apk

      - name: Set HAS_DEBUG_ARTIFACT to true
        run: echo '::set-env name=HAS_DEBUG_ARTIFACT::true'

        # Release APK

      - name: Build Signed APK
        working-directory: android
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: ${{ env.SIGNED_RELEASE_FILE }}

      - name: Set HAS_RELEASE_ARTIFACT to true
        run: echo '::set-env name=HAS_RELEASE_ARTIFACT::true'

      - name: Send email indicate success
        if: ${{success()}}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          body: "<h2>Build job of ${{github.repository}} <mark>SUCCEEDED</mark>.</h2><br/><h4>Branch: ${{github.ref}}</h4><br/>Generated Debug artifact----------<b>${{env.HAS_DEBUG_ARTIFACT}}</b><br/><br/>GeneratedRelease artifact----------<b>${{env.HAS_RELEASE_ARTIFACT}}</b><br/><br/>Build triggered by <b>${{github.actor}}</b>"
          to: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_USERNAME}}
          content_type: text/html

      - name: Send email indicate failure
        if: ${{failure() || cancelled()}}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          body: "<h2>Build job of ${{github.repository}} <mark>FAILED</mark>.</h2><br/><h4>Branch: ${{github.ref}}</h4><br/>Generated Debug artifact----------<b>${{env.HAS_DEBUG_ARTIFACT}}</b><br/><br/>Generated Release artifact----------<b>${{env.HAS_RELEASE_ARTIFACT}}</b><br/><br/>Build triggered by <b>${{github.actor}}</b>"
          to: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_USERNAME}}
          content_type: text/html
